version: "2"
services:
  mysql-db:
    container_name: mysql-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "dev"
      MYSQL_USER: "devuser"
      MYSQL_PASSWORD: "devpass"
      MYSQL_ROOT_PASSWORD: "devpass"
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      inner:
        aliases:
          - mysql-db
networks:
  inner: {}
volumes:
  mysql-db: {}